# Generated by Django 3.2.16 on 2023-03-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=64, unique=True)),
                ('pwd', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('type', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
